# Generated by Django 5.2.7 on 2025-10-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_studentdetals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentDetals',
            new_name='studentDetails',
        ),
    ]
