# Generated by Django 5.2.7 on 2025-10-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_rename_studentdetals_studentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
